-- 3. The Pizza Runner team now wants to add an additional ratings system that allows customers to rate their runner, 
-- how would you design an additional table for this new dataset - generate a schema for this new table 
-- and insert your own data for ratings for each successful customer order between 1 to 5.

-- order_id here will allow us to identify the corresponding runner and customer in the runner_orders and customer_orders tables respectively
-- rating_time and rating_comment columns are added to capture information that enable actionable insights in the real world
SET search_path TO pizza_runner;

DROP TABLE IF EXISTS runner_ratings;
CREATE TABLE runner_ratings (
    rating_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer REFERENCES runner_orders (order_id),
    rating_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    rating integer CHECK (rating > 0 AND rating < 6),
    rating_comment varchar(100)
);

INSERT INTO runner_ratings (order_id, rating, rating_comment)
VALUES
  (1, 5, 'Fast and friendly!'),
  (2, 4, 'Pizza was a bit cold but the runner was nice.'),
  (3, 5, 'Excellent service.'),
  (4, 3, 'Took a long time to find my house.'),
  (5, 5, 'Great attitude!'),
  (7, 4, 'Very polite.'),
  (8, 2, 'Runner dropped the box!'),
  (10, 5, 'Incredible speed, thank you.');
